# Generated by Django 5.0.dev20230323094401 on 2023-03-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.IntegerField(),
        ),
    ]
